export const phoneMask = [
  "+",
  "7",
  " ",
  "(",
  /\d/,
  /\d/,
  /\d/,
  ")",
  " ",
  /\d/,
  /\d/,
  /\d/,
  "-",
  /\d/,
  /\d/,
  "-",
  /\d/,
  /\d/,
];

export const API_URL_FOR_UPLOADS = `http://localhost:3001/public/uploads`;
export const notificationMessages = {
  error: "Something went wrong! Try again later.",
  success_operation: "Your action was successfull!",
};

export const text = {
  login: "Login",
  password: "Password",
  lastname: "Last name",
  password_value_error: "Minimal lenght of password is 5",
  password_validation_error: "Password is required",
  password_description: "Password should include at least 5 symbols",
  email_empty_error: "Email is required",
  email_validation_error: "Email is invalid",
  password_placeholder: "Enter password...",
  email_placeholder: "Enter email...",
  registration: "Registration",
  phone_placeholder: "+7 (___) ___-__-__",
  firstname_empty_error: "First name is required",
  lastname_empty_error: "Last name is required",
  firstname_placeholder: "Enter first name",
  lastname_placeholder: "Enter last name",
  birthdate_placeholder: "Pick your birth date",
  firstname: "First Name",
  phone: "Phone",
  email: "Email",
  app_name: "FlaatsRent",
  signin_message: "Already have an account? Sign-in",
  registration_message: "Dont have an account? Register now",
  birth_date: "Birth date",
  authenication: "Authenication",
  registrate: "Registrate",
  error_while_fetching_flats:
    "Sorry, there was an error while getting flats. Try again later",
  guests: "Guests",
  duration: "Any week",
  place: "Any place",
};
